name: Auto Merge Trusted PRs

on:
  pull_request:
    types: [labeled, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'autotrusted')
    steps:
    - name: Merge PR
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --merge --admin --delete-branch --repo somerandomscripts/WF-social-data
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
